name: Build and Upload omod

on:
 push:
    branches:
     - develop
 workflow_dispatch:
env:
  ORG_NAME: Bahmni-HWC
  EVENT_TYPE: openmrs-module-openhmis.inventory

jobs:
  build:
    name: build and upload omod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_MVN_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.S3_MVN_SECRET_KEY }}
        aws-region: ap-southeast-1
    - name: Build with Maven
      run: mvn clean -U deploy -Dcheckstyle.skip -DskipTests

  trigger-dependent-repos:
    name: Trigger Workflows
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependent-repos: [ 'bahmni-india-package' ]
    steps:
      - name: Create repository_dispatch
        env:
          REPOSITORY_NAME: ${{ matrix.dependent-repos }}
        run: |
          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
          if [ $trigger_result == 204 ];then
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
          else
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
            cat trigger_response.txt
            exit 1
          fi
